services:
  - type: web
    name: sakhi-voice
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --prefer-offline --no-audit --no-fund && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_AGORA_APP_ID
        value: b6bfc5ea3dac445cb951beb9d373ddc5
      - key: AGORA_APP_ID
        value: b6bfc5ea3dac445cb951beb9d373ddc5
      - key: AGORA_APP_CERTIFICATE
        value: c7d61b3b003f4f5d97f40c783f37116d
      - key: AGORA_CUSTOMER_ID
        value: 4484034496dd4b56bf6e53d2d8a195cc
      - key: AGORA_CUSTOMER_SECRET
        value: ae3b66db366744b88e51df1f32d3a2e1
      - key: VOBIZ_AUTH_ID
        value: MA_Y0UIJABP
      - key: VOBIZ_AUTH_TOKEN
        value: OJ2JClaUVKqqnOgfsRbp323RkdZbyv6YFgfU37m9ulQMtrHYP2Y10idVU8I5KOk8
      - key: NEXT_PUBLIC_VOBIZ_AUTH_ID
        value: MA_Y0UIJABP
      - key: NEXT_PUBLIC_VOBIZ_PHONE_NUMBER
        value: 1800-72544-24
